---
title: "Clase 8"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(dslabs)
# https://bradleyboehmke.github.io/HOML/kmeans.html
mnist <- dslabs::read_mnist()
```

```{r}
mnist <- dslabs::read_mnist()
glimpse(mnist)
```

```{r}
features <- mnist$train$images
glimpse(features)
```

```{r}
str(features[1,0])
d <- matrix(features[1,], nrow = 28, byrow = TRUE)

```

```{r}
library(reshape2)
digito<-melt(d)
#longData<-longData[longData$value!=0,]
digito

```

```{r}
ggplot(digito, aes(x = Var2, y = Var1)) +
  geom_raster(aes(fill=value))
```

```{r}
library(patchwork)

p <- function(i){
    d <- matrix(features[i,], nrow = 28, byrow = TRUE)
    digito<-melt(d)
    ggplot(digito, aes(x = Var2, y = Var1)) +
    geom_raster(aes(fill=value)) +  coord_fixed() +
      theme_void() + theme(legend.position = "none")+scale_y_reverse()
  }
```


```{r}
p(1) + p(2) + p(3) + p(4) + p(5) + p(6) + p(7) + p(8) + p(9) + p(10)
```


```{r}
labels_dig <- mnist$train$labels
labels_dig
```

```{r}
features <- mnist$train$images
glimpse(features)

```

```{r}
x <- features[2,] %>% as.data.frame()
for(i in 1:10000) {
  if(labels_dig[i] == 0){
    x <- rbind(x, features[i,] %>% as.data.frame())
  }
}
ggplot(x,aes(x=.))+geom_histogram(binwidth = 1)+xlim(230, 260)
```
```{r}
x <- features[1,] %>% as.data.frame()
for(i in 1:10000) {
  if(labels_dig[i] == 5){
    x <- rbind(x, features[i,] %>% as.data.frame())
  }
}
ggplot(x,aes(x=.))+geom_histogram(binwidth = 1)+xlim(230, 260)
```


```{r}
x <- features[3,] %>% as.data.frame()
for(i in 1:10000) {
  if(labels_dig[i] == 4){
    x <- rbind(x, features[i,] %>% as.data.frame())
  }
}
ggplot(x,aes(x=.))+geom_histogram(binwidth = 1)+xlim(230, 260)
```


```{r}
x <- features[4,] %>% as.data.frame()
for(i in 1:10000) {
  if(labels_dig[i] == 1){
    x <- rbind(x, features[i,] %>% as.data.frame())
  }
}
ggplot(x,aes(x=.))+geom_histogram(binwidth = 1)+xlim(230, 260)
```

```{r}
x <- features[5,] %>% as.data.frame()
for(i in 1:10000) {
  if(labels_dig[i] == 9){
    x <- rbind(x, features[i,] %>% as.data.frame())
  }
}
ggplot(x,aes(x=.))+geom_histogram(binwidth = 1)+xlim(230, 260)
```

```{r}
x <- features[6,] %>% as.data.frame()
for(i in 1:10000) {
  if(labels_dig[i] == 2){
    x <- rbind(x, features[i,] %>% as.data.frame())
  }
}
ggplot(x,aes(x=.))+geom_histogram(binwidth = 1)+xlim(230, 260)
```

```{r}
mnist_clustering <- kmeans(features, centers = 10, nstart = 10)
```
```{r}
str(mnist_clustering)

```


```{r}
# Extract cluster centers
mnist_centers <- mnist_clustering$centers
glimpse(mnist_centers)
```
```{r}
dc<-matrix(mnist_centers[1,], nrow = 28, byrow = TRUE)
    digito<-melt(dc)
    ggplot(digito, aes(x = Var2, y = Var1)) +
    geom_raster(aes(fill=value)) +  coord_fixed() +
      theme_void() + theme(legend.position = "none")+scale_y_reverse()
```
```{r}
dc1<-matrix(mnist_centers[2,], nrow = 28, byrow = TRUE)
    digito<-melt(dc1)
    ggplot(digito, aes(x = Var2, y = Var1)) +
    geom_raster(aes(fill=value)) +  coord_fixed() +
      theme_void() + theme(legend.position = "none")+scale_y_reverse()
```
```{r}
dc2<-matrix(mnist_centers[3,], nrow = 28, byrow = TRUE)
    digito<-melt(dc2)
    ggplot(digito, aes(x = Var2, y = Var1)) +
    geom_raster(aes(fill=value)) +  coord_fixed() +
      theme_void() + theme(legend.position = "none")+scale_y_reverse()
```

```{r}
dc3<-matrix(mnist_centers[4,], nrow = 28, byrow = TRUE)
    digito<-melt(dc3)
    ggplot(digito, aes(x = Var2, y = Var1)) +
    geom_raster(aes(fill=value)) +  coord_fixed() +
      theme_void() + theme(legend.position = "none")+scale_y_reverse()
```

```{r}
dc4<-matrix(mnist_centers[5,], nrow = 28, byrow = TRUE)
    digito<-melt(dc4)
    ggplot(digito, aes(x = Var2, y = Var1)) +
    geom_raster(aes(fill=value)) +  coord_fixed() +
      theme_void() + theme(legend.position = "none")+scale_y_reverse()
```

```{r}
dc5<-matrix(mnist_centers[6,], nrow = 28, byrow = TRUE)
    digito<-melt(dc5)
    ggplot(digito, aes(x = Var2, y = Var1)) +
    geom_raster(aes(fill=value)) +  coord_fixed() +
      theme_void() + theme(legend.position = "none")+scale_y_reverse()
```
```{r}
dc6<-matrix(mnist_centers[7,], nrow = 28, byrow = TRUE)
    digito<-melt(dc6)
    ggplot(digito, aes(x = Var2, y = Var1)) +
    geom_raster(aes(fill=value)) +  coord_fixed() +
      theme_void() + theme(legend.position = "none")+scale_y_reverse()
```
```{r}
dc7<-matrix(mnist_centers[8,], nrow = 28, byrow = TRUE)
    digito<-melt(dc7)
    ggplot(digito, aes(x = Var2, y = Var1)) +
    geom_raster(aes(fill=value)) +  coord_fixed() +
      theme_void() + theme(legend.position = "none")+scale_y_reverse()
```
```{r}
dc8<-matrix(mnist_centers[9,], nrow = 28, byrow = TRUE)
    digito<-melt(dc8)
    ggplot(digito, aes(x = Var2, y = Var1)) +
    geom_raster(aes(fill=value)) +  coord_fixed() +
      theme_void() + theme(legend.position = "none")+scale_y_reverse()
```

```{r}
dc9<-matrix(mnist_centers[10,], nrow = 28, byrow = TRUE)
    digito<-melt(dc9)
    ggplot(digito, aes(x = Var2, y = Var1)) +
    geom_raster(aes(fill=value)) +  coord_fixed() +
      theme_void() + theme(legend.position = "none")+scale_y_reverse()
```

```{r}
# Plot typical cluster digits
par(mfrow = c(2, 5), mar=c(0.5, 0.5, 0.5, 0.5))
layout(matrix(seq_len(nrow(mnist_centers)), 2, 5, byrow = FALSE))
for(i in seq_len(nrow(mnist_centers))) {
  image(matrix(mnist_centers[i, ], 28, 28)[, 28:1],xaxt="n", yaxt="n")
}
```


```{r}
# Plot typical cluster digits
par(mfrow = c(2, 5), mar=c(0.5, 0.5, 0.5, 0.5))
layout(matrix(seq_len(nrow(mnist_centers)), 2, 5, byrow = FALSE))
for(i in seq_len(nrow(mnist_centers))) {
  image(matrix(mnist_centers[i, ], 28, 28)[, 28:1],xaxt="n", yaxt="n")
}
```

```{r}
# Create mode function
mode_fun <- function(x){  
  which.max(tabulate(x))
}

 

mnist_comparison <- data.frame(
  cluster = mnist_clustering$cluster,
  actual = mnist$train$labels
) %>%
  group_by(cluster) %>%
  mutate(mode = mode_fun(actual)) %>%
  ungroup() %>%
  mutate_all(factor, levels = 0:9)

 

# Create confusion matrix and plot results
yardstick::conf_mat(
  mnist_comparison, 
  truth = actual, 
  estimate = mode
) %>%
  autoplot(type = 'heatmap')
```

